<div data-layer="Notifications" class="Notifications w-96 h-[489px] relative bg-white rounded-2xl overflow-hidden">
    <div data-layer="Frame 8" class="Frame8 size-96 left-0 top-[75px] absolute overflow-hidden">
        <div data-layer="Not1" class="Not1 w-96 h-24 left-0 top-0 absolute">
            <div data-layer="Rectangle 16" class="Rectangle16 w-96 h-24 left-0 top-0 absolute bg-neutral-300"></div>
            <div data-layer="Complete the UI design of Landing Page for FoodVentures. 2h" class="CompleteTheUiDesignOfLandingPageForFoodventures2h left-[24px] top-[10px] absolute justify-start"><span class="text-black text-base font-normal font-['Inter'] leading-6">Complete the</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> </span><span class="text-black text-base font-semibold font-['Inter'] leading-6">UI design</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> </span><span class="text-black text-base font-normal font-['Inter'] leading-6">of Landing</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> <br/></span><span class="text-black text-base font-normal font-['Inter'] leading-6">Page for</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> </span><span class="text-black text-base font-semibold font-['Inter'] leading-6">FoodVentures</span><span class="text-black text-base font-medium font-['Inter'] leading-6">.</span><span class="text-black text-xl font-medium font-['Inter'] leading-6"> </span><span class="text-zinc-400 text-xs font-medium font-['Inter'] leading-6">2h</span></div>
            <div data-layer="Priority: High" class="PriorityHigh left-[24px] top-[62px] absolute justify-start"><span class="text-black text-xs font-medium font-['Inter'] leading-6">Priority: </span><span class="text-red-600 text-xs font-medium font-['Inter'] leading-6">High</span><span class="text-black text-xs font-medium font-['Inter'] leading-6"> </span></div>
            <img data-layer="Rectangle 20" class="Rectangle20 size-12 left-[303px] top-[22px] absolute rounded-sm" src="https://placehold.co/52x52" />
        </div>
        <div data-layer="Not1" class="Not1 w-96 h-24 left-0 top-[97px] absolute">
            <div data-layer="Rectangle 16" class="Rectangle16 w-96 h-24 left-0 top-0 absolute bg-neutral-300"></div>
            <div data-layer="Complete the UI design of Landing Page for FoodVentures. 2h" class="CompleteTheUiDesignOfLandingPageForFoodventures2h left-[24px] top-[10px] absolute justify-start"><span class="text-black text-base font-normal font-['Inter'] leading-6">Complete the</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> </span><span class="text-black text-base font-semibold font-['Inter'] leading-6">UI design</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> </span><span class="text-black text-base font-normal font-['Inter'] leading-6">of Landing</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> <br/></span><span class="text-black text-base font-normal font-['Inter'] leading-6">Page for</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> </span><span class="text-black text-base font-semibold font-['Inter'] leading-6">Travel Days</span><span class="text-black text-base font-medium font-['Inter'] leading-6">.</span><span class="text-black text-xl font-medium font-['Inter'] leading-6"> </span><span class="text-zinc-400 text-xs font-medium font-['Inter'] leading-6">2h</span></div>
            <div data-layer="Priority: High" class="PriorityHigh left-[24px] top-[62px] absolute justify-start"><span class="text-black text-xs font-medium font-['Inter'] leading-6">Priority: </span><span class="text-red-600 text-xs font-medium font-['Inter'] leading-6">High</span><span class="text-black text-xs font-medium font-['Inter'] leading-6"> </span></div>
            <img data-layer="Rectangle 20" class="Rectangle20 size-12 left-[303px] top-[22px] absolute rounded-sm" src="https://placehold.co/52x52" />
        </div>
        <div data-layer="Not1" class="Not1 w-96 h-24 left-0 top-[194px] absolute">
            <div data-layer="Rectangle 16" class="Rectangle16 w-96 h-24 left-0 top-0 absolute bg-neutral-300"></div>
            <div data-layer="Complete the UI design of Landing Page for FoodVentures. 2h" class="CompleteTheUiDesignOfLandingPageForFoodventures2h left-[24px] top-[10px] absolute justify-start"><span class="text-black text-base font-normal font-['Inter'] leading-6">Complete the</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> </span><span class="text-black text-base font-semibold font-['Inter'] leading-6">Mobile app design<br/></span><span class="text-black text-base font-normal font-['Inter'] leading-6"> for</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> </span><span class="text-black text-base font-semibold font-['Inter'] leading-6">Pet Warden</span><span class="text-black text-base font-medium font-['Inter'] leading-6">.</span><span class="text-black text-xl font-medium font-['Inter'] leading-6"> </span><span class="text-zinc-400 text-xs font-medium font-['Inter'] leading-6">2h</span></div>
            <div data-layer="Priority: High" class="PriorityHigh left-[24px] top-[62px] absolute justify-start"><span class="text-black text-xs font-medium font-['Inter'] leading-6">Priority: </span><span class="text-red-600 text-xs font-medium font-['Inter'] leading-6">Extremely High</span><span class="text-black text-xs font-medium font-['Inter'] leading-6"> </span></div>
            <img data-layer="Rectangle 20" class="Rectangle20 size-12 left-[303px] top-[22px] absolute rounded-sm" src="https://placehold.co/52x52" />
        </div>
        <div data-layer="Not1" class="Not1 w-96 h-24 left-0 top-[291px] absolute">
            <div data-layer="Rectangle 16" class="Rectangle16 w-96 h-24 left-0 top-0 absolute bg-neutral-300"></div>
            <div data-layer="Complete the UI design of Landing Page for FoodVentures. 2h" class="CompleteTheUiDesignOfLandingPageForFoodventures2h left-[24px] top-[10px] absolute justify-start"><span class="text-black text-base font-normal font-['Inter'] leading-6">Complete the</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> entire design</span><span class="text-black text-base font-normal font-['Inter'] leading-6"> for</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> <br/></span><span class="text-black text-base font-semibold font-['Inter'] leading-6">Juice Slider</span><span class="text-black text-base font-medium font-['Inter'] leading-6">.</span><span class="text-black text-xl font-medium font-['Inter'] leading-6"> </span><span class="text-zinc-400 text-xs font-medium font-['Inter'] leading-6">2h</span></div>
            <div data-layer="Priority: High" class="PriorityHigh left-[24px] top-[62px] absolute justify-start"><span class="text-black text-xs font-medium font-['Inter'] leading-6">Priority: </span><span class="text-red-600 text-xs font-medium font-['Inter'] leading-6">High</span><span class="text-black text-xs font-medium font-['Inter'] leading-6"> </span></div>
            <img data-layer="Rectangle 20" class="Rectangle20 size-12 left-[303px] top-[22px] absolute rounded-sm" src="https://placehold.co/52x52" />
        </div>
        <div data-layer="Not1" class="Not1 w-96 h-24 left-0 top-[388px] absolute">
            <div data-layer="Rectangle 16" class="Rectangle16 w-96 h-24 left-0 top-0 absolute bg-neutral-300"></div>
            <div data-layer="Complete the UI design of Landing Page for FoodVentures. 2h" class="CompleteTheUiDesignOfLandingPageForFoodventures2h left-[24px] top-[10px] absolute justify-start"><span class="text-black text-base font-normal font-['Inter'] leading-6">Complete the</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> entire design</span><span class="text-black text-base font-normal font-['Inter'] leading-6"> for</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> <br/></span><span class="text-black text-base font-semibold font-['Inter'] leading-6">Juice Slider</span><span class="text-black text-base font-medium font-['Inter'] leading-6">.</span><span class="text-black text-xl font-medium font-['Inter'] leading-6"> </span><span class="text-zinc-400 text-xs font-medium font-['Inter'] leading-6">2h</span></div>
            <div data-layer="Priority: High" class="PriorityHigh left-[24px] top-[62px] absolute justify-start"><span class="text-black text-xs font-medium font-['Inter'] leading-6">Priority: </span><span class="text-red-600 text-xs font-medium font-['Inter'] leading-6">High</span><span class="text-black text-xs font-medium font-['Inter'] leading-6"> </span></div>
            <img data-layer="Rectangle 20" class="Rectangle20 size-12 left-[303px] top-[22px] absolute rounded-sm" src="https://placehold.co/52x52" />
        </div>
        <div data-layer="Not1" class="Not1 w-96 h-24 left-0 top-[485px] absolute">
            <div data-layer="Rectangle 16" class="Rectangle16 w-96 h-24 left-0 top-0 absolute bg-neutral-300"></div>
            <div data-layer="Complete the UI design of Landing Page for FoodVentures. 2h" class="CompleteTheUiDesignOfLandingPageForFoodventures2h left-[24px] top-[10px] absolute justify-start"><span class="text-black text-base font-normal font-['Inter'] leading-6">Complete the</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> entire design</span><span class="text-black text-base font-normal font-['Inter'] leading-6"> for</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> <br/></span><span class="text-black text-base font-semibold font-['Inter'] leading-6">Juice Slider</span><span class="text-black text-base font-medium font-['Inter'] leading-6">.</span><span class="text-black text-xl font-medium font-['Inter'] leading-6"> </span><span class="text-zinc-400 text-xs font-medium font-['Inter'] leading-6">2h</span></div>
            <div data-layer="Priority: High" class="PriorityHigh left-[24px] top-[62px] absolute justify-start"><span class="text-black text-xs font-medium font-['Inter'] leading-6">Priority: </span><span class="text-red-600 text-xs font-medium font-['Inter'] leading-6">High</span><span class="text-black text-xs font-medium font-['Inter'] leading-6"> </span></div>
            <img data-layer="Rectangle 20" class="Rectangle20 size-12 left-[303px] top-[22px] absolute rounded-sm" src="https://placehold.co/52x52" />
        </div>
        <div data-layer="Not1" class="Not1 w-96 h-24 left-0 top-[582px] absolute">
            <div data-layer="Rectangle 16" class="Rectangle16 w-96 h-24 left-0 top-0 absolute bg-neutral-300"></div>
            <div data-layer="Complete the UI design of Landing Page for FoodVentures. 2h" class="CompleteTheUiDesignOfLandingPageForFoodventures2h left-[24px] top-[10px] absolute justify-start"><span class="text-black text-base font-normal font-['Inter'] leading-6">Complete the</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> entire design</span><span class="text-black text-base font-normal font-['Inter'] leading-6"> for</span><span class="text-black text-base font-medium font-['Inter'] leading-6"> <br/></span><span class="text-black text-base font-semibold font-['Inter'] leading-6">Juice Slider</span><span class="text-black text-base font-medium font-['Inter'] leading-6">.</span><span class="text-black text-xl font-medium font-['Inter'] leading-6"> </span><span class="text-zinc-400 text-xs font-medium font-['Inter'] leading-6">2h</span></div>
            <div data-layer="Priority: High" class="PriorityHigh left-[24px] top-[62px] absolute justify-start"><span class="text-black text-xs font-medium font-['Inter'] leading-6">Priority: </span><span class="text-red-600 text-xs font-medium font-['Inter'] leading-6">High</span><span class="text-black text-xs font-medium font-['Inter'] leading-6"> </span></div>
            <img data-layer="Rectangle 20" class="Rectangle20 size-12 left-[303px] top-[22px] absolute rounded-sm" src="https://placehold.co/52x52" />
        </div>
    </div>
    <div data-layer="Today" class="Today left-[32px] top-[47px] absolute justify-start text-zinc-400 text-sm font-medium font-['Inter']">Today</div>
    <div data-layer="Notifications" class="Notifications left-[32px] top-[17px] absolute justify-start text-black text-base font-semibold font-['Inter']">Notifications</div>
    <div data-layer="Vector" class="Vector size-5 left-[325px] top-[17px] absolute bg-white outline outline-2 outline-offset-[-1px] outline-white"></div>
    <div data-layer="Vector" class="Vector size-7 left-[322.80px] top-[13.15px] absolute bg-cyan-900"></div>
</div>